#!/usr/bin/env bash
#This script transfers a file from the client to the server

if [ "$4" ] 
then
    scp -o StrictHostKeyChecking=no "$4" "$1" "$3"@"$2":~/
elif [ "$3" ] 
then
    scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
