#!/usr/bin/env bash
#This script configures nginx of an ubuntu
# machine in a maaner that makes the HTTP response contain the custom header

sudo sed -i '62a\\n        add_header X-Served-By $hostname always;' /etc/nginx/nginx.conf
sudo service nginx restart
