#!/usr/bin/env bash
#Displays hours from 0 to 12 and minutes from 1 to 59

hour=0

while ((hour <= 12));
do
    echo "Hour: $hour"
    minutes=1
    while ((minutes <= 59));
    do
        echo "$minutes"
        ((minutes++))
    done
    ((hour++))
done