#!/usr/bin/env bash
# This cript ensures Nginx is running as a the nginx user
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sed -i 's/\s*#?\s*user .*/user nginx/' /etc/nginx/nginx.conf
pkill apache2
su -c 'service nginx start' nginx
